---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      containers:
      - name: recommender
        image: juestnow/vpa-recommender:0.5.0
        imagePullPolicy: Always
        args:
          - "--v=4"
          - "--stderrthreshold=info"
          - "--storage=prometheus"
          - "--prometheus-address=http://prometheus-k8s.monitoring.svc:9090"
          - "--prometheus-cadvisor-job-name=kubelet"
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: http-metrics
          containerPort: 8942
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    k8s-app: vpa-recommender
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8942
    protocol: TCP
  selector:
    app: vpa-recommender
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpa-recommender
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http-metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: vpa-recommender
