apiVersion: v1
data:
  process-exporter.yaml: |
    process_names:
      - name: "{{.Comm}}"
        cmdline:
        - '.+'


kind: ConfigMap
metadata:
  creationTimestamp: null
  name: process-config
  namespace: monitoring
