kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 20Gi
