apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: nginx-vts-exporter
  name: nginx-vts-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: api
    port: 9913
    protocol: TCP
    targetPort: 9913
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: nginx-vts-exporter
  name: nginx-vts-exporter
  namespace: monitoring
subsets:
- addresses:
  - ip: 192.168.2.186
  ports:
  - name: api
    port: 9913
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: nginx-vts-exporter
  name: nginx-vts-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: api
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      k8s-app: nginx-vts-exporter
