kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  storageClassName: nfs-storage 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
