apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  namespace: monitoring
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - name: prometheus
        image: prom/prometheus:v2.9.2
        args:
          - '--config.file=/etc/prometheus/prometheus.yaml'
          - '--storage.tsdb.retention=7d'
          - '--web.enable-lifecycle'
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 2048M
          limits:
            cpu: 500m
            memory: 2048M
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: rules-volume
          mountPath: /etc/prometheus-rules
        - name: prometheus-data
          mountPath: /prometheus/data
        - name: sys-time
          mountPath: /etc/localtime
        - name: etcd-certs
          mountPath: /certs
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-core
      - name: rules-volume
        configMap:
          name: prometheus-rules
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-pvc 
      - name: sys-time
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: etcd-certs
        secret:
          secretName: etcd-certs
