apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups: 
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: 
    - get
    - list
    - watch
- apiGroups: 
  - ""
  resources:
  - configmaps
  verbs: 
    - get
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs: 
    - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- nonResourceURLs: 
  - /metrics
  verbs: 
    - get