apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    operated-prometheus: "true"
  name: prometheus-operated
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
